### PR TITLE
Built in Types fixes

### PR DESCRIPTION
**Pull request by ChrisJollyAU**
- Force bigint to decimal if needed
- Fix potential nulls with DateOnly/TimeOnly ConfigureParameter
- Manually round a decimal to the correct scale (both parameter and string literal). With the way we handle the parameters it doesn't do any rounding. The test bases do expect a certain rounding (e.g. a decimal of 101.7 entered in with a scale of 0 should return 102)
- BigInt is now mapped to decimal(20,0)
- A plain store type of `decimal` is mapped to `decimal(18, 0)` like SQL Server
- System.Decimal is mapped to `decimal(18,2)`
- Store type of date can be also mapped to DateTime (in addition to dateonly)
- Store type of time can also be mapped to TimeSpan (in addition to timeonly)

### CODE REVIEW

**Comment by ChrisJollyAU** [comment]
@lauxjpn Can you take a look at your test detection system. The tests that are failing all pass locally in VS and I can't find any other mention of those tests in the logs

**Comment by lauxjpn** [comment]
The report seems to be correct, the tests did not pass in those runs. You can see the failed test executions it in the [raw log of the run](https://github.com/CirrusRedOrg/EntityFrameworkCore.Jet/commit/9520f5f8c57dcbd12cf43966bd31f6ce99e0cd42/checks/18142870000/logs), or you can download the `test-results` artifact from the corresponding [workflow action run](https://github.com/CirrusRedOrg/EntityFrameworkCore.Jet/actions/runs/6675175783) (scroll to the bottom of the summary to find the artifacts).

For example, the result for the `Scaffolding.JetDatabaseModelFactoryTest.ConcurrencyToken_is_set_for_rowVersion` test case with `ace_2010_oledb_x86` resulted in:

```
System.Data.OleDb.OleDbException : Syntax error in field definition.

at System.Data.OleDb.OleDbCommand.ExecuteCommandText(Object& executeResult)
at System.Data.OleDb.OleDbCommand.ExecuteReaderInternal(CommandBehavior behavior, String method)
at System.Data.OleDb.OleDbCommand.ExecuteNonQuery()
at EntityFrameworkCore.Jet.Data.JetCommand.ExecuteNonQueryCore() in D:\a\EntityFrameworkCore.Jet\EntityFrameworkCore.Jet\src\EFCore.Jet.Data\JetCommand.cs:line 291
at EntityFrameworkCore.Jet.Data.JetCommand.<>c.<ExecuteNonQuery>b__47_0(Int32 _, JetCommand command) in D:\a\EntityFrameworkCore.Jet\EntityFrameworkCore.Jet\src\EFCore.Jet.Data\JetCommand.cs:line 248
at System.Linq.Enumerable.Aggregate[TSource,TAccumulate](IEnumerable`1 source, TAccumulate seed, Func`3 func)
at EntityFrameworkCore.Jet.Data.JetCommand.ExecuteNonQuery() in D:\a\EntityFrameworkCore.Jet\EntityFrameworkCore.Jet\src\EFCore.Jet.Data\JetCommand.cs:line 247
at EntityFrameworkCore.Jet.FunctionalTests.TestUtilities.JetTestStore.<>c.<ExecuteNonQuery>b__24_0(DbCommand command) in D:\a\EntityFrameworkCore.Jet\EntityFrameworkCore.Jet\test\EFCore.Jet.FunctionalTests\TestUtilities\JetTestStore.cs:line 192
at EntityFrameworkCore.Jet.FunctionalTests.TestUtilities.JetTestStore.ExecuteCommand[T](DbConnection connection, Func`2 execute, String sql, Boolean useTransaction, Object[] parameters) in D:\a\EntityFrameworkCore.Jet\EntityFrameworkCore.Jet\test\EFCore.Jet.FunctionalTests\TestUtilities\JetTestStore.cs:line 311
at EntityFrameworkCore.Jet.FunctionalTests.TestUtilities.JetTestStore.<>c__31`1.<Execute>b__31_0(<>f__AnonymousType65`5 state) in D:\a\EntityFrameworkCore.Jet\EntityFrameworkCore.Jet\test\EFCore.Jet.FunctionalTests\TestUtilities\JetTestStore.cs:line 250
at Microsoft.EntityFrameworkCore.ExecutionStrategyExtensions.<>c__DisplayClass12_0`2.<Execute>b__0(DbContext _, TState s)
at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.<>c__DisplayClass28_0`2.<Execute>b__0(DbContext context, TState state)
at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteImplementation[TState,TResult](Func`3 operation, Func`3 verifySucceeded, TState state)
at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
at Microsoft.EntityFrameworkCore.ExecutionStrategyExtensions.Execute[TState,TResult](IExecutionStrategy strategy, TState state, Func`2 operation, Func`2 verifySucceeded)
at Microsoft.EntityFrameworkCore.ExecutionStrategyExtensions.Execute[TState,TResult](IExecutionStrategy strategy, TState state, Func`2 operation)
at EntityFrameworkCore.Jet.FunctionalTests.TestUtilities.JetTestStore.Execute[T](DbConnection connection, Func`2 execute, String sql, Boolean useTransaction, Object[] parameters) in D:\a\EntityFrameworkCore.Jet\EntityFrameworkCore.Jet\test\EFCore.Jet.FunctionalTests\TestUtilities\JetTestStore.cs:line 241
at EntityFrameworkCore.Jet.FunctionalTests.TestUtilities.JetTestStore.ExecuteNonQuery(DbConnection connection, String sql, Object[] parameters) in D:\a\EntityFrameworkCore.Jet\EntityFrameworkCore.Jet\test\EFCore.Jet.FunctionalTests\TestUtilities\JetTestStore.cs:line 192
at EntityFrameworkCore.Jet.FunctionalTests.TestUtilities.JetTestStore.ExecuteNonQuery(String sql, Object[] parameters) in D:\a\EntityFrameworkCore.Jet\EntityFrameworkCore.Jet\test\EFCore.Jet.FunctionalTests\TestUtilities\JetTestStore.cs:line 189
at EntityFrameworkCore.Jet.FunctionalTests.Scaffolding.JetDatabaseModelFactoryTest.Test(String[] createSqls, IEnumerable`1 tables, IEnumerable`1 schemas, Action`1 asserter, String cleanupSql) in D:\a\EntityFrameworkCore.Jet\EntityFrameworkCore.Jet\test\EFCore.Jet.FunctionalTests\Scaffolding\JetDatabaseModelFactoryTest.cs:line 2035
at EntityFrameworkCore.Jet.FunctionalTests.Scaffolding.JetDatabaseModelFactoryTest.Test(String createSql, IEnumerable`1 tables, IEnumerable`1 schemas, Action`1 asserter, String cleanupSql) in D:\a\EntityFrameworkCore.Jet\EntityFrameworkCore.Jet\test\EFCore.Jet.FunctionalTests\Scaffolding\JetDatabaseModelFactoryTest.cs:line 2019
at EntityFrameworkCore.Jet.FunctionalTests.Scaffolding.JetDatabaseModelFactoryTest.ConcurrencyToken_is_set_for_rowVersion() in D:\a\EntityFrameworkCore.Jet\EntityFrameworkCore.Jet\test\EFCore.Jet.FunctionalTests\Scaffolding\JetDatabaseModelFactoryTest.cs:line 1358
at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
at System.Reflection.MethodBaseInvoker.InterpretedInvoke_Method(Object obj, IntPtr* args)
at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
```

I am not able to reproduce the `Syntax error in field definition.` exception on the docker environments.

@ChrisJollyAU I can take another look at this, after you have rebased the feature branch on top of the latest `master` branch.

**Comment by lauxjpn** [comment]
After your merge to the top of the `master` branch, this error is now reproducible in the corresponding docker environment.

**Comment by ChrisJollyAU** [comment]
@lauxjpn With that one at least the column type for the row version was wrong. It was `varbinary(8)` but became `rowversion` when I did some updates (which is not supported)

**Comment by lauxjpn** [comment]
Check the others as well. There is likely a logical explanation for their failure as well. If not, just ping me again and I'll take another look at it.

**Comment by ChrisJollyAU** [comment]
@lauxjpn The other 3 are no longer available

**Pull request merged**
