### PR TITLE
Add compatibility info for 8.0 series

### PR DESCRIPTION
**Pull request by ChrisJollyAU**

### CODE REVIEW

**Comment by ChrisJollyAU** [comment]
[skip ci]

**Comment by lauxjpn** [comment]
Okay, it should work now (the #182 test PR behaved the way we want it to).

**Comment by ChrisJollyAU** [comment]
Well, the merge button is available, but it still looks to run all the tests anyway

**Comment by lauxjpn** [comment]
It does definitely work for new PRs, even those that have been created using the GitHub interface (e.g. when making a change to the `README.MD` file directly on GitHub). It will only trigger a dummy workflow that will result in a successful status. Can be verified by taking a look a the still open #183 PR.

Its possible that this behaves differently for already existing PRs.

**Comment by ChrisJollyAU** [comment]
> Its possible that this behaves differently for already existing PRs.

Fair enough

**Pull request merged**
